### ISSUE TITLE
undefined reference to `pthread_atfork'

### ISSUE THREAD

**Issue by Crafter76** [wg/wrk#379]
Centos 7.5 
after make I get
...
LINK wrk
obj/lib/libcrypto.a(threads_pthread.o): In function `fork_once_func':
threads_pthread.c:(.text+0x16): undefined reference to `pthread_atfork'
collect2: ошибка: выполнение ld завершилось с кодом возврата 1
make: *** [wrk] Ошибка 1

**Comment by headius** [comment]
Also happening on Ubuntu 16.04.

**Comment by headius** [comment]
Tag 4.1.0 builds ok on Ubuntu 16.04. I notice parts of the build use -pthread instead of -lpthread...which may line up with some suggestions here: https://github.com/openssl/openssl/issues/3884

**Comment by DavisFrench** [comment]
I get this as well when trying to install wrk in a dockerfile using the latest Ubuntu image, which is 18.04 I believe.

**Comment by naftulikay** [comment]
Also affected on Ubuntu 18.04.

**Comment by wg** [comment]
Thank you all for the reports! Looks like library link order matters with the latest OpenSSL, so I've updated that.

**Comment by ReK2Fernandez** [comment]
Hello Im having this same issue under
```
Ubuntu 18.04.3 LTS
```
with:
```
  8%] Linking CXX executable test_cypher_suites
/usr/lib/x86_64-linux-gnu/libcrypto.a(threads_pthread.o): In function `fork_once_func':
(.text+0x16): undefined reference to `pthread_atfork'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/build.make:113: recipe for target 'libraries/fc/test/crypto/test_cypher_suites' failed
make[2]: *** [libraries/fc/test/crypto/test_cypher_suites] Error 1
CMakeFiles/Makefile2:789: recipe for target 'libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all' failed
make[1]: *** [libraries/fc/test/crypto/CMakeFiles/test_cypher_suites.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2
```
none of the work around did work for me, because I can't downgrade to that version with apt
