### ISSUE TITLE
asyn.c undefined reference to `setcontext' when building on alpine:3.4

### ISSUE THREAD

**Issue by nardeas** [wg/wrk#263]
I'm tying to build wrk inside an alpine container but it returns the following error:

```
./libcrypto.a(async_posix.o): In function `ASYNC_is_capable':
async_posix.c:(.text+0x1e): undefined reference to `getcontext'
./libcrypto.a(async_posix.o): In function `async_fibre_makecontext':
async_posix.c:(.text+0x75): undefined reference to `getcontext'
async_posix.c:(.text+0xe2): undefined reference to `makecontext'
./libcrypto.a(async.o): In function `async_fibre_swapcontext.constprop.2':
async.c:(.text+0x36): undefined reference to `setcontext'
collect2: error: ld returned 1 exit status
make[3]: *** [link_app.] Error 1
Makefile.shared:187: recipe for target 'link_app.' failed
make[3]: Leaving directory '/app/wrk/obj/openssl-1.1.0d'
Makefile:6010: recipe for target 'apps/openssl' failed
make[2]: Leaving directory '/app/wrk/obj/openssl-1.1.0d'
make[2]: *** [apps/openssl] Error 2
make[1]: *** [all] Error 2
Makefile:128: recipe for target 'all' failed
make[1]: Leaving directory '/app/wrk/obj/openssl-1.1.0d'
make: *** [obj/lib/libssl.a] Error 2
Makefile:90: recipe for target 'obj/lib/libssl.a' failed
```

I'm using `alpine:3.4` as the base image with `alpine-sdk` metapackage for build dependencies. Then I'm simply cloning the repo and doing `make` in my Dockerfile which results in the error above.

Any ideas what I might be doing wrong or if this is an issue with `wrk` itself?

**Comment by wg** [comment]
That error is occurring while building the bundled OpenSSL, looks like it doesn't build properly on Alpine. Since it seems you're using Docker the best bet is probably to use a debian or ubuntu image instead.

**Comment by gruebel** [comment]
@nardeas You just have to add the **linux-headers** package
```
apk add --no-cache linux-headers
```
at least that solved the problem for me, when I tried to compile on `alpine:3.7`

**Comment by maikelvl** [comment]
Running the following fixed this issue for me on `alpine:3.9`:

```bash
sed -i 's/no-idea/no-idea no-async/' Makefile
```

**Comment by wg** [comment]
Thanks for the updates! I'm including `alpine:latest` in the CI config now and it looks to build fine with the latest OpenSSL.
